package appcontrolealuno;

import javax.swing.JDesktopPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author desenv01
 */
public class AppControleAluno extends javax.swing.JFrame {

    private static final long serialVersionUID = 7816475544715004504L;

    /**
     * Creates new form AppGProtEl
     */
    public AppControleAluno() {
        initComponents();
        setLocationRelativeTo(null);
    }
    // Preenche dados do Cliente selecionado na chamada da rotina

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuPrimeiraContagem = new javax.swing.JMenuItem();
        jMenuPrimeiraContagem1 = new javax.swing.JMenuItem();
        jMenuPrimeiraContagem2 = new javax.swing.JMenuItem();
        jMenuPrimeiraContagem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("008");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("008");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Cliente Ótica ");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jMenuPrimeiraContagem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuPrimeiraContagem.setText("Aluno");
        jMenuPrimeiraContagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrimeiraContagemActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPrimeiraContagem);

        jMenuPrimeiraContagem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuPrimeiraContagem1.setText("Professor");
        jMenuPrimeiraContagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrimeiraContagem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPrimeiraContagem1);

        jMenuPrimeiraContagem2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuPrimeiraContagem2.setText("Turma");
        jMenuPrimeiraContagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrimeiraContagem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPrimeiraContagem2);

        jMenuPrimeiraContagem3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuPrimeiraContagem3.setText("AlunosTurma");
        jMenuPrimeiraContagem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrimeiraContagem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPrimeiraContagem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("  Sair");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7KeyPressed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuPrimeiraContagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrimeiraContagemActionPerformed
        AlunoMain frm = new AlunoMain();   // Cria na memória a variável StatusClienteMain
        jPanelPrincipal.add(frm);                          // Mosta na tela principal o StatusClienteMain
        int x = (jPanelPrincipal.getWidth() / 2) - (frm.getWidth() / 2);
        int y = (jPanelPrincipal.getHeight() / 2) - (frm.getHeight() / 2);
        frm.setLocation(x, y); // Centraliza o StatusClienteMain
        frm.setVisible(true); // Coloca o frm visível dentro do quadrado
    }//GEN-LAST:event_jMenuPrimeiraContagemActionPerformed

    private void jMenuPrimeiraContagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrimeiraContagem1ActionPerformed
        ProfessorMain frm = new ProfessorMain();   // Cria na memória a variável StatusClienteMain
        jPanelPrincipal.add(frm);                          // Mosta na tela principal o StatusClienteMain
        int x = (jPanelPrincipal.getWidth() / 2) - (frm.getWidth() / 2);
        int y = (jPanelPrincipal.getHeight() / 2) - (frm.getHeight() / 2);
        frm.setLocation(x, y); // Centraliza o StatusClienteMain
        frm.setVisible(true); // Coloca o frm visível dentro do quadrado
    }//GEN-LAST:event_jMenuPrimeiraContagem1ActionPerformed

    private void jMenuPrimeiraContagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrimeiraContagem2ActionPerformed
        // TODO add your handling code here:
        TurmaMain frm = new TurmaMain();   // Cria na memória a variável StatusClienteMain
        jPanelPrincipal.add(frm);                          // Mosta na tela principal o StatusClienteMain
        int x = (jPanelPrincipal.getWidth() / 2) - (frm.getWidth() / 2);
        int y = (jPanelPrincipal.getHeight() / 2) - (frm.getHeight() / 2);
        frm.setLocation(x, y); // Centraliza o StatusClienteMain
        frm.setVisible(true); // Coloca o frm visível dentro do quadrado
    }//GEN-LAST:event_jMenuPrimeiraContagem2ActionPerformed

    private void jMenuPrimeiraContagem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrimeiraContagem3ActionPerformed

        TurmaAlunoMain frm = new TurmaAlunoMain();   // Cria na memória a variável StatusClienteMain
        jPanelPrincipal.add(frm);                          // Mosta na tela principal o StatusClienteMain
        int x = (jPanelPrincipal.getWidth() / 2) - (frm.getWidth() / 2);
        int y = (jPanelPrincipal.getHeight() / 2) - (frm.getHeight() / 2);
        frm.setLocation(x, y); // Centraliza o StatusClienteMain
        frm.setVisible(true); // Coloca o frm visível dentro do quadrado
    }//GEN-LAST:event_jMenuPrimeiraContagem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppControleAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>




        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AppControleAluno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuPrimeiraContagem;
    private javax.swing.JMenuItem jMenuPrimeiraContagem1;
    private javax.swing.JMenuItem jMenuPrimeiraContagem2;
    private javax.swing.JMenuItem jMenuPrimeiraContagem3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables

}
