/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcontrolealuno;

import DAO.AlunoDAO;
import DAO.ProfessorDAO;
import DAO.TurmaDAO;
import TO.AlunoTO;
import TO.ProfessorTO;
import TO.ProfessorTurmaTO;
import TO.TurmaAlunoTO;
import TO.TurmaTO;
import db.DaoException;
import exceptions.ValidacaoException;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author desenv01
 */
public class ProfessorTurmaMain extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -2809442742901146299L;

    String titulo = "";
    int qtdDeTurma = 0;

    private DefaultTableModel getTableModel() {
        return (DefaultTableModel) jTableProfessorTurma.getModel();
    }

    /**
     * Creates new form AppGProtEl
     */
    public ProfessorTurmaMain() {

        initComponents();
        this.setEnabled(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtNomeProfessor.requestFocus();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfessorTurma = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButtonDinheiro = new javax.swing.JButton();
        jTxtTurma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonConfirmaTurma = new javax.swing.JButton();
        jTxtSerie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtNomeProfessor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTxtMateria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtidTurma = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtidProf = new javax.swing.JTextField();

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("008");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("008");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        jTableProfessorTurma.setAutoCreateRowSorter(true);
        jTableProfessorTurma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableProfessorTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "idTurma", "Turma", "Série"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProfessorTurma.setShowHorizontalLines(false);
        jTableProfessorTurma.setShowVerticalLines(false);
        jTableProfessorTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProfessorTurmaMouseClicked(evt);
            }
        });
        jTableProfessorTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableProfessorTurmaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProfessorTurma);
        if (jTableProfessorTurma.getColumnModel().getColumnCount() > 0) {
            jTableProfessorTurma.getColumnModel().getColumn(0).setMinWidth(65);
            jTableProfessorTurma.getColumnModel().getColumn(0).setPreferredWidth(65);
            jTableProfessorTurma.getColumnModel().getColumn(0).setMaxWidth(65);
            jTableProfessorTurma.getColumnModel().getColumn(2).setMinWidth(80);
            jTableProfessorTurma.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableProfessorTurma.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro de Turma por Professor");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButtonDinheiro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDinheiro.setText("Confirma entrada");
        jButtonDinheiro.setActionCommand("Confirma ");
        jButtonDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDinheiroActionPerformed(evt);
            }
        });
        jButtonDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonDinheiroKeyPressed(evt);
            }
        });

        jTxtTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtTurma.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtTurma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtTurmaFocusGained(evt);
            }
        });
        jTxtTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTurmaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Série....:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("idTurma:");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonConfirmaTurma.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonConfirmaTurma.setText("Confirma turma");
        jButtonConfirmaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaTurmaActionPerformed(evt);
            }
        });
        jButtonConfirmaTurma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonConfirmaTurmaKeyPressed(evt);
            }
        });

        jTxtSerie.setEditable(false);
        jTxtSerie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtSerie.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSerieActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Professor:");

        jTxtNomeProfessor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtNomeProfessor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeProfessorActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTxtMateria.setEditable(false);
        jTxtMateria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtMateria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMateriaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Matéria...:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Turma..:");

        jTxtidTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtidTurma.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtidTurma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtidTurmaFocusGained(evt);
            }
        });
        jTxtidTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtidTurmaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("idProf.....:");

        jTxtidProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtidProf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtidProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtidProfActionPerformed(evt);
            }
        });

        jDesktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButtonDinheiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButtonConfirmaTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtNomeProfessor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtidTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtidProf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonConfirmaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel8))
                                        .addGap(17, 17, 17)
                                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                                .addComponent(jTxtidTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTxtSerie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(jTxtTurma, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addComponent(jButtonDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addComponent(jTxtidProf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTxtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jTxtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(428, 428, 428)))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtidProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jTxtNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTxtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel12)))
                        .addGap(42, 42, 42)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtidTurma)
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTxtTurma)))
                        .addGap(6, 6, 6)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTxtSerie)))
                        .addGap(39, 39, 39)
                        .addComponent(jButtonConfirmaTurma)
                        .addGap(54, 54, 54)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7KeyPressed


    private void jTxtTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTurmaActionPerformed
        // Busca nome da turma e coloca descricao e pula para quantidade:
        if (!jTxtTurma.getText().equals("")) {
            // localiza turma pelo numero
            TurmaTO turma = new TurmaTO();
            try {
                //detalhar aluno
                turma = TurmaDAO.detalharTurmaNumero(jTxtTurma.getText());
            } catch (DaoException ex) {
                Logger.getLogger(ProfessorTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro consulta BD!");
                jTxtNomeProfessor.requestFocus();
            }
            if (turma == null) {
                JOptionPane.showMessageDialog(this, "Turma " + jTxtTurma.getText() + " \nNão cadastrada!");
                jTxtTurma.requestFocus();
                return;
            } else {
                jTxtidTurma.setText(String.valueOf(turma.getIdturma()));
                jTxtTurma.setText(turma.getNumeroturma());
                jTxtSerie.setText(turma.getSerie());
            }
            //sua internet caiu? Meu celular acabpi a bateria kkkkk ok  Roda ai... 
            //não está trazendo o nome do aluno 
        }
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtTurma.setBackground(new Color(255, 0, 102));
                jTxtTurma.requestFocus();
            }
        });
    }//GEN-LAST:event_jTxtTurmaActionPerformed

    private void inicioGravacaoTurmaAluno() throws NumberFormatException, HeadlessException {
        
        // Pede confirmação a criação professor|turma
        Object[] options = {"Sim", "Não"};
        int q = JOptionPane.showOptionDialog(null,
                "Confirma Criação da Turma ?", "Saída",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[1]);
        if (q == JOptionPane.YES_OPTION) {
        
            // Monta array objetos para gravar
            // Declarar Movimento TO

            ArrayList<ProfessorTurmaTO> ta = new ArrayList<>();
            System.out.println("+++++ fora " + qtdDeTurma);
            for (int i = 1; i <= qtdDeTurma; i++) {
                System.out.println("+++++ i =  " + i );
                System.out.println("+++++ dentro " + jTableProfessorTurma.getValueAt(i, 0).toString());
                ProfessorTurmaTO to = new ProfessorTurmaTO();
                to.setIdprofessor(Integer.parseInt(jTxtidProf.getText()));
                to.setNome(jTxtNomeProfessor.getText());
                to.setMateria(jTxtMateria.getText());
                to.setIdturma(Integer.parseInt(jTableProfessorTurma.getValueAt(i, 0).toString()));
                to.setNumeroturma(jTableProfessorTurma.getValueAt(i, 1).toString());
                to.setSerie(jTableProfessorTurma.getValueAt(i, 2).toString());
                ta.add(to);
            }
            
            //ArrayList<RelEntradaTO> relEntrada;
            try {
                //Grava dados no banco
                DAO.ProfessorTurmaDAO.inserirProfessorTurma(ta); 
                } catch (DaoException | SQLException ex) {
                Logger.getLogger(ProfessorTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao gravar entrada");
                return;
            }

            // limpa campos da tela
            getTableModel().setRowCount(0);
            jTxtNomeProfessor.setText("");
            jTxtMateria.setText("");
            jTxtidTurma.setText("");
            jTxtTurma.setText("");
            jTxtSerie.setText("");
            // Imprime tiket venda
            /*
            try {
                // Pergunta se imprime ou gera PDF
                Object[] options1 = {"Impressora", "Tela"};
                int q1 = JOptionPane.showOptionDialog(null,
                        "O relatório será?", "Saída",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                        options1, options1[1]);
                if (q1 == JOptionPane.YES_OPTION) {

                    // compilacao do JRXML
                    JasperReport report = JasperCompileManager.compileReport(geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.jrxml");
                    JasperPrint print = JasperFillManager.fillReport(report, null, new JRBeanCollectionDataSource(relEntrada));
                        // exportacao do relatorio para outro formato, no caso PDF 
                    //JasperExportManager.exportReportToPdfFile(print, geral.Geral.getDiretorioAtual() + "\\Relatorios\\RelatorioClientes.pdf");  
                    //JasperViewer.viewReport(print, false);
                    JasperPrintManager.printPage(print, 0, false);

                } else {
                    JasperReport report = JasperCompileManager.compileReport(geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.jrxml");
                    JasperPrint print = JasperFillManager.fillReport(report, null, new JRBeanCollectionDataSource(relEntrada));
                    // exportacao do relatorio para outro formato, no caso PDF 
                    JasperExportManager.exportReportToPdfFile(print, geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.pdf");
                    JasperViewer.viewReport(print, false);
                }
            } catch (JRException | ValidacaoException ex) {
                Logger.getLogger(TurmaAlunoMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao imprimir entrada!");
            }
            */
        }
 
    }
            

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode() == 10) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableProfessorTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProfessorTurmaMouseClicked
       /*
        Double total = Double.valueOf(jTxtTotalGeral.getText());
        Double excluido = Double.valueOf(jTableMovCx.getValueAt(jTableMovCx.getSelectedRow(), 4).toString());
        jTxtTotalGeral.setText(String.valueOf(duasDecimais.format(total - excluido)));
        getTableModel().removeRow(jTableMovCx.getSelectedRow());
        jTxtNumItens.setText(String.valueOf(Integer.parseInt(jTxtNumItens.getText()) - 1));
        if (Integer.parseInt(jTxtNumItens.getText()) <= 1) {
            jLabelItem.setText("Item");
        }
        */
    }//GEN-LAST:event_jTableProfessorTurmaMouseClicked

    private void jTableProfessorTurmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProfessorTurmaKeyPressed
       /*
        Double total = Double.valueOf(jTxtTotalGeral.getText());
        Double excluido = Double.valueOf(jTableMovCx.getValueAt(jTableMovCx.getSelectedRow(), 4).toString());
        jTxtTotalGeral.setText(String.valueOf(duasDecimais.format(total - excluido)));
        getTableModel().removeRow(jTableMovCx.getSelectedRow());
        jTxtNumItens.setText(String.valueOf(Integer.parseInt(jTxtNumItens.getText()) - 1));
        if (Integer.parseInt(jTxtNumItens.getText()) <= 1) {
            jLabelItem.setText("Item");
        }
        */
    }//GEN-LAST:event_jTableProfessorTurmaKeyPressed

    private void jButtonDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDinheiroKeyPressed
        inicioGravacaoTurmaAluno();
    }//GEN-LAST:event_jButtonDinheiroKeyPressed

    private void jButtonDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDinheiroActionPerformed

        inicioGravacaoTurmaAluno();

    }//GEN-LAST:event_jButtonDinheiroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     /*
        try {
            if (veEstoqueConsulta()) {
                ItemMain frm = new ItemMain("EntradaFC", jTxtNome.getText().trim());
                jDesktopPane.add(frm);
                int x = (jDesktopPane.getWidth() / 2) - (frm.getWidth() / 2);
                int y = (jDesktopPane.getHeight() / 2) - (frm.getHeight() / 2);
                frm.setLocation(x, y);
                frm.show();
            } else {
                ItemMain frmSe = new ItemMain("EntradaFC", jTxtNome.getText().trim());
                jDesktopPane.add(frmSe);
                int x = (jDesktopPane.getWidth() / 2) - (frmSe.getWidth() / 2);
                int y = (jDesktopPane.getHeight() / 2) - (frmSe.getHeight() / 2);
                frmSe.setLocation(x, y);
                frmSe.show();

            }
        } catch (DaoException ex) {
            Logger.getLogger(TurmaAlunoMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtTurmaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtTurmaFocusGained
        jTxtTurma.setBackground(new Color(255, 0, 102));
     //   jTxtQtd.setBackground(jTxtDataNascimento.getBackground());
    }//GEN-LAST:event_jTxtTurmaFocusGained

    private void jButtonConfirmaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaTurmaActionPerformed
            ProfessorTurmaTO it;
            if (jTxtNomeProfessor.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Falta professor!");
                jTxtNomeProfessor.requestFocus();
                return;
            }
            if (jTxtidTurma.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Falta turma!");
                jTxtidTurma.requestFocus();
                return;
            }
            String[] rowData = new String[3];
            rowData[0] = jTxtidTurma.getText();
            rowData[1] = jTxtTurma.getText();
            rowData[2] = jTxtSerie.getText();
            
            getTableModel().addRow(rowData);
                        
            jTxtidTurma.setText("");
            jTxtNomeProfessor.setBackground(new Color(255, 0, 102));
            jTxtTurma.setText("");
            jTxtSerie.setText("");

            qtdDeTurma = qtdDeTurma + 1;
            
            // Foco no código
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jTxtidTurma.setBackground(new Color(255, 0, 102));
                    jTxtidTurma.requestFocus();
                }
            });
    }//GEN-LAST:event_jButtonConfirmaTurmaActionPerformed

    private void jButtonConfirmaTurmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonConfirmaTurmaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmaTurmaKeyPressed

    private void jTxtNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeProfessorActionPerformed
        if (!jTxtNomeProfessor.getText().equals("")) {
            // localiza professor pelo numero
            ProfessorTO prof = new ProfessorTO();
            try {
                //detalhar professor
                prof = ProfessorDAO.detalharProfessorNome(jTxtNomeProfessor.getText());
            } catch (DaoException ex) {
                Logger.getLogger(ProfessorTurmaMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro consulta BD!");
                jTxtNomeProfessor.requestFocus();
            }
            if (prof == null) {
                JOptionPane.showMessageDialog(this, "Professor(a) " + jTxtNomeProfessor.getText() + " \nNão cadastrado(a)!");
                jTxtNomeProfessor.requestFocus();
                return;
            } else {
                jTxtMateria.setText(prof.getMateria());
                jTxtidProf.setText(String.valueOf(prof.getIdprofessor()));
                jTxtNomeProfessor.setText(prof.getNome());
            }
        }
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtTurma.setBackground(new Color(255, 0, 102));
                jTxtTurma.requestFocus();
            }
        });
    }//GEN-LAST:event_jTxtNomeProfessorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*
        FornecedorMain frm = new FornecedorMain("EntradaFC");
        getDesktopPane().add(frm);
        int x = (getDesktopPane().getWidth() / 2) - (frm.getWidth() / 2);
        int y = (getDesktopPane().getHeight() / 2) - (frm.getHeight() / 2);
        frm.setLocation(x, y);
        frm.show();
        */
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSerieActionPerformed

    private void jTxtidTurmaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtidTurmaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidTurmaFocusGained

    private void jTxtidTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtidTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidTurmaActionPerformed

    private void jTxtidProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtidProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidProfActionPerformed

    private void jTxtMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMateriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonConfirmaTurma;
    private javax.swing.JButton jButtonDinheiro;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfessorTurma;
    private static javax.swing.JTextField jTxtMateria;
    private static javax.swing.JTextField jTxtNomeProfessor;
    private static javax.swing.JTextField jTxtSerie;
    private static javax.swing.JTextField jTxtTurma;
    private static javax.swing.JTextField jTxtidProf;
    private static javax.swing.JTextField jTxtidTurma;
    // End of variables declaration//GEN-END:variables

}
