/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appcontrolealuno;

import DAO.AlunoDAO;
import DAO.TurmaDAO;
import TO.AlunoTO;
import TO.TurmaAlunoTO;
import TO.TurmaTO;
import db.DaoException;
import exceptions.ValidacaoException;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author desenv01
 */
public class TurmaAlunoMain extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -2809442742901146299L;

    String titulo = "";
    int qtdDeAlunos = 0;

    private DefaultTableModel getTableModel() {
        return (DefaultTableModel) jTableTurmaAluno.getModel();
    }

    /**
     * Creates new form AppGProtEl
     */
    public TurmaAlunoMain() {

        initComponents();
        this.setEnabled(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtCodigoTurma.requestFocus();
            }
        });

    }
    static void setDadosTurma(String turma, String serie) {
        jTxtCodigoTurma.setText(turma);
        jTxtSerie.setText(serie);
        jTxtNome.requestFocus();
    }
    static void setDadosAluno(int idaluno, String nome, String sexo, String datanascimento) {
        jTxtidAluno.setText(String.valueOf(idaluno));
        jTxtNome.setText(nome);
        jTxtSexo.setText(sexo);
        jTxtDataNascimento.setText(datanascimento);
        
        jTxtNome.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurmaAluno = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTxtDataNascimento = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButtonDinheiro = new javax.swing.JButton();
        jTxtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonConfirmaAluno = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTxtSexo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtCodigoTurma = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTxtSerie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtidAluno = new javax.swing.JTextField();

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("008");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("008");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane.setBackground(new java.awt.Color(255, 255, 255));

        jTableTurmaAluno.setAutoCreateRowSorter(true);
        jTableTurmaAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableTurmaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "idAluno", "Nome", "Sexo", " Data Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTurmaAluno.setShowHorizontalLines(false);
        jTableTurmaAluno.setShowVerticalLines(false);
        jTableTurmaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTurmaAlunoMouseClicked(evt);
            }
        });
        jTableTurmaAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableTurmaAlunoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTurmaAluno);
        if (jTableTurmaAluno.getColumnModel().getColumnCount() > 0) {
            jTableTurmaAluno.getColumnModel().getColumn(0).setMinWidth(65);
            jTableTurmaAluno.getColumnModel().getColumn(0).setPreferredWidth(65);
            jTableTurmaAluno.getColumnModel().getColumn(0).setMaxWidth(65);
            jTableTurmaAluno.getColumnModel().getColumn(2).setMinWidth(80);
            jTableTurmaAluno.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableTurmaAluno.getColumnModel().getColumn(2).setMaxWidth(80);
            jTableTurmaAluno.getColumnModel().getColumn(3).setMinWidth(95);
            jTableTurmaAluno.getColumnModel().getColumn(3).setPreferredWidth(95);
            jTableTurmaAluno.getColumnModel().getColumn(3).setMaxWidth(95);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro de Alunos por Turma");

        jTxtDataNascimento.setEditable(false);
        jTxtDataNascimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtDataNascimento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDataNascimentoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButtonDinheiro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDinheiro.setText("Confirma entrada");
        jButtonDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDinheiroActionPerformed(evt);
            }
        });
        jButtonDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonDinheiroKeyPressed(evt);
            }
        });

        jTxtNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtNomeFocusGained(evt);
            }
        });
        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Sexo:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("idAluno:");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonConfirmaAluno.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonConfirmaAluno.setText("Confirma aluno");
        jButtonConfirmaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaAlunoActionPerformed(evt);
            }
        });
        jButtonConfirmaAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonConfirmaAlunoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nasc.:");

        jTxtSexo.setEditable(false);
        jTxtSexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtSexo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSexoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Turma:");

        jTxtCodigoTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtCodigoTurma.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtCodigoTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoTurmaActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTxtSerie.setEditable(false);
        jTxtSerie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtSerie.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSerieActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Série:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Nome:");

        jTxtidAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtidAluno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtidAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtidAlunoFocusGained(evt);
            }
        });
        jTxtidAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtidAlunoActionPerformed(evt);
            }
        });

        jDesktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtDataNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButtonDinheiro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButtonConfirmaAluno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtCodigoTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jTxtidAluno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jButtonConfirmaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addComponent(jTxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(163, 163, 163))
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addComponent(jTxtSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addGap(121, 121, 121))
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addComponent(jTxtNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtidAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel11))
                                .addGap(27, 27, 27)
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                        .addComponent(jTxtCodigoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtCodigoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(50, 50, 50))
                            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtidAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jButtonConfirmaAluno)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7KeyPressed


    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // Busca nome do aluno e coloca descricao e pula para quantidade:
        if (!jTxtNome.getText().equals("")) {
            // localiza turma pelo numero
            AlunoTO aluno = new AlunoTO();
            try {
                //detalhar aluno
                aluno = AlunoDAO.detalharAlunoNome(jTxtNome.getText());
            } catch (DaoException ex) {
                Logger.getLogger(TurmaAlunoMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro consulta BD!");
                jTxtCodigoTurma.requestFocus();
            }
            if (aluno == null) {
                JOptionPane.showMessageDialog(this, "Aluno " + jTxtNome.getText() + " \nNão cadastrado!");
                jTxtNome.requestFocus();
                return;
            } else {
                jTxtidAluno.setText(String.valueOf(aluno.getIdaluno()));
                jTxtNome.setText(aluno.getNome());
                jTxtSexo.setText(aluno.getSexo());
                jTxtDataNascimento.setText(aluno.getDatanascimento());
            }
            //sua internet caiu? Meu celular acabpi a bateria kkkkk ok  Roda ai... 
            //não está trazendo o nome do aluno 
        }
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtNome.setBackground(new Color(255, 0, 102));
                jTxtNome.requestFocus();
            }
        });
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void inicioGravacaoTurmaAluno() throws NumberFormatException, HeadlessException {
        
        // Pede confirmação a criação turma aluno
        Object[] options = {"Sim", "Não"};
        int q = JOptionPane.showOptionDialog(null,
                "Confirma Criação da Turma ?", "Saída",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[1]);
        if (q == JOptionPane.YES_OPTION) {
        
            // Monta array objetos para gravar
            // Declarar Movimento TO

            ArrayList<TurmaAlunoTO> ta = new ArrayList<>();
            System.out.println("+++++ fora " + qtdDeAlunos);
            for (int i = 1; i <= qtdDeAlunos; i++) {
                System.out.println("+++++ dentro " + jTableTurmaAluno.getValueAt(i, 0).toString());
                TurmaAlunoTO to = new TurmaAlunoTO();
                to.setIdturma(Integer.parseInt(jTxtCodigoTurma.getText()));
                to.setSerie(jTxtSerie.getText());
                to.setIdaluno(Integer.parseInt(jTableTurmaAluno.getValueAt(i, 0).toString()));
                to.setNome(jTableTurmaAluno.getValueAt(i, 1).toString());
                to.setSexo(jTableTurmaAluno.getValueAt(i, 2).toString());
                to.setDatanascimento(jTableTurmaAluno.getValueAt(i, 3).toString());
                ta.add(to);
            }
            
            //ArrayList<RelEntradaTO> relEntrada;
            try {
                //Grava dados no banco
                DAO.TurmaAlunoDAO.inserirTurmaAluno(ta);
                            } catch (DaoException | SQLException ex) {
                Logger.getLogger(TurmaAlunoMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao gravar entrada");
                return;
            }

            // limpa campos da tela
            getTableModel().setRowCount(0);
            jTxtCodigoTurma.setText("");
            jTxtSerie.setText("");
            jTxtidAluno.setText("");
            jTxtNome.setText("");
            jTxtSexo.setText("");
            jTxtDataNascimento.setText("");
            // Imprime tiket venda
            /*
            try {
                // Pergunta se imprime ou gera PDF
                Object[] options1 = {"Impressora", "Tela"};
                int q1 = JOptionPane.showOptionDialog(null,
                        "O relatório será?", "Saída",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                        options1, options1[1]);
                if (q1 == JOptionPane.YES_OPTION) {

                    // compilacao do JRXML
                    JasperReport report = JasperCompileManager.compileReport(geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.jrxml");
                    JasperPrint print = JasperFillManager.fillReport(report, null, new JRBeanCollectionDataSource(relEntrada));
                        // exportacao do relatorio para outro formato, no caso PDF 
                    //JasperExportManager.exportReportToPdfFile(print, geral.Geral.getDiretorioAtual() + "\\Relatorios\\RelatorioClientes.pdf");  
                    //JasperViewer.viewReport(print, false);
                    JasperPrintManager.printPage(print, 0, false);

                } else {
                    JasperReport report = JasperCompileManager.compileReport(geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.jrxml");
                    JasperPrint print = JasperFillManager.fillReport(report, null, new JRBeanCollectionDataSource(relEntrada));
                    // exportacao do relatorio para outro formato, no caso PDF 
                    JasperExportManager.exportReportToPdfFile(print, geral.Geral.getDiretorioAtual() + "\\Relatorios\\TiketEntrada.pdf");
                    JasperViewer.viewReport(print, false);
                }
            } catch (JRException | ValidacaoException ex) {
                Logger.getLogger(TurmaAlunoMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao imprimir entrada!");
            }
            */
        }
 
    }
            

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode() == 10) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDataNascimentoActionPerformed

    private void jTableTurmaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTurmaAlunoMouseClicked
       /*
        Double total = Double.valueOf(jTxtTotalGeral.getText());
        Double excluido = Double.valueOf(jTableMovCx.getValueAt(jTableMovCx.getSelectedRow(), 4).toString());
        jTxtTotalGeral.setText(String.valueOf(duasDecimais.format(total - excluido)));
        getTableModel().removeRow(jTableMovCx.getSelectedRow());
        jTxtNumItens.setText(String.valueOf(Integer.parseInt(jTxtNumItens.getText()) - 1));
        if (Integer.parseInt(jTxtNumItens.getText()) <= 1) {
            jLabelItem.setText("Item");
        }
        */
    }//GEN-LAST:event_jTableTurmaAlunoMouseClicked

    private void jTableTurmaAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableTurmaAlunoKeyPressed
       /*
        Double total = Double.valueOf(jTxtTotalGeral.getText());
        Double excluido = Double.valueOf(jTableMovCx.getValueAt(jTableMovCx.getSelectedRow(), 4).toString());
        jTxtTotalGeral.setText(String.valueOf(duasDecimais.format(total - excluido)));
        getTableModel().removeRow(jTableMovCx.getSelectedRow());
        jTxtNumItens.setText(String.valueOf(Integer.parseInt(jTxtNumItens.getText()) - 1));
        if (Integer.parseInt(jTxtNumItens.getText()) <= 1) {
            jLabelItem.setText("Item");
        }
        */
    }//GEN-LAST:event_jTableTurmaAlunoKeyPressed

    private void jButtonDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonDinheiroKeyPressed
        inicioGravacaoTurmaAluno();
    }//GEN-LAST:event_jButtonDinheiroKeyPressed

    private void jButtonDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDinheiroActionPerformed

        inicioGravacaoTurmaAluno();

    }//GEN-LAST:event_jButtonDinheiroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        AlunoMain frmSe = new AlunoMain("TurmaAlunoMain");
        jDesktopPane.add(frmSe);
        int x = (jDesktopPane.getWidth() / 2) - (frmSe.getWidth() / 2);
        int y = (jDesktopPane.getHeight() / 2) - (frmSe.getHeight() / 2);
        frmSe.setLocation(x, y);
        frmSe.show();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNomeFocusGained
        jTxtNome.setBackground(new Color(255, 0, 102));
     //   jTxtQtd.setBackground(jTxtDataNascimento.getBackground());
    }//GEN-LAST:event_jTxtNomeFocusGained

    private void jButtonConfirmaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaAlunoActionPerformed
            TurmaAlunoTO it;
            if (jTxtCodigoTurma.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Falta turma!");
                jTxtCodigoTurma.requestFocus();
                return;
            }
            if (jTxtidAluno.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Falta aluno!");
                jTxtidAluno.requestFocus();
                return;
            }
            String[] rowData = new String[4];
            rowData[0] = jTxtidAluno.getText();
            rowData[1] = jTxtNome.getText();
            rowData[2] = jTxtSexo.getText();
            rowData[3] = jTxtDataNascimento.getText();
            
            getTableModel().addRow(rowData);
                        
            jTxtidAluno.setText("");
            jTxtCodigoTurma.setBackground(new Color(255, 0, 102));
            jTxtNome.setText("");
            jTxtSexo.setText("");
            jTxtDataNascimento.setText("");

            qtdDeAlunos = qtdDeAlunos + 1;
            
            // Foco no código
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    jTxtidAluno.setBackground(new Color(255, 0, 102));
                    jTxtidAluno.requestFocus();
                }
            });
    }//GEN-LAST:event_jButtonConfirmaAlunoActionPerformed

    private void jButtonConfirmaAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonConfirmaAlunoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmaAlunoKeyPressed

    private void jTxtCodigoTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoTurmaActionPerformed
        if (!jTxtCodigoTurma.getText().equals("")) {
            // localiza turma pelo numero
            TurmaTO turma = new TurmaTO();
            try {
                //detalhar turma
                turma = TurmaDAO.detalharTurmaNumero(jTxtCodigoTurma.getText());
            } catch (DaoException ex) {
                Logger.getLogger(TurmaAlunoMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage() + " \nErro consulta BD!");
                jTxtCodigoTurma.requestFocus();
            }
            if (turma == null) {
                JOptionPane.showMessageDialog(this, "Turma " + jTxtCodigoTurma.getText() + " \nNão cadastrada!");
                jTxtCodigoTurma.requestFocus();
                return;
            } else {
                jTxtSerie.setText(turma.getSerie());
            }
        }
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                jTxtNome.setBackground(new Color(255, 0, 102));
                jTxtNome.requestFocus();
            }
        });
    }//GEN-LAST:event_jTxtCodigoTurmaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        TurmaMain frm = new TurmaMain("TurmaAlunoMain");
        jDesktopPane.add(frm);
        int x = (jDesktopPane.getWidth() / 2) - (frm.getWidth() / 2);
        int y = (jDesktopPane.getHeight() / 2) - (frm.getHeight() / 2);
        frm.setLocation(x, y);
        frm.show();

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSexoActionPerformed

    private void jTxtidAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtidAlunoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidAlunoFocusGained

    private void jTxtidAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtidAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtidAlunoActionPerformed

    private void jTxtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSerieActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonConfirmaAluno;
    private javax.swing.JButton jButtonDinheiro;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTurmaAluno;
    private static javax.swing.JTextField jTxtCodigoTurma;
    private static javax.swing.JTextField jTxtDataNascimento;
    private static javax.swing.JTextField jTxtNome;
    private static javax.swing.JTextField jTxtSerie;
    private static javax.swing.JTextField jTxtSexo;
    private static javax.swing.JTextField jTxtidAluno;
    // End of variables declaration//GEN-END:variables

}
